'use client';

import React, { useState, useEffect } from 'react';
import { Navbar } from '../components/Navbar';
import { OpportunityCard } from '../components/OpportunityCard';
import { LiveStreamFeed } from '../components/LiveStreamFeed';
import { Opportunity, IngestedPost } from '../types';
import { INITIAL_OPPORTUNITIES, INITIAL_LIVE_POSTS } from '../lib/mock-data';
import { CheckCircle2, ShieldCheck, RefreshCw } from 'lucide-react';

const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';

export default function MarketerReviewDesk() {
  const [opportunities, setOpportunities] = useState<Opportunity[]>(INITIAL_OPPORTUNITIES);
  const [livePosts, setLivePosts] = useState<IngestedPost[]>(INITIAL_LIVE_POSTS);
  const [approvedCount, setApprovedCount] = useState(1);
  const [isRefreshing, setIsRefreshing] = useState(false);

  // Fetch pending review queue from backend
  const fetchReviewQueue = async () => {
    try {
      setIsRefreshing(true);
      const res = await fetch(`${API_BASE}/api/review-queue`);
      if (res.ok) {
        const data = await res.json();
        const list = data.queue || data.opportunities;
        if (list && list.length > 0) {
          const mapped: Opportunity[] = list.map((row: any) => ({
            id: row.thread_id,
            thread_data: {
              thread_id: row.thread_id,
              subreddit: row.subreddit,
              title: row.title,
              body: row.body || '',
              author: row.author,
              permalink: row.permalink,
              created_utc: row.created_utc || Date.now() / 1000,
            },
            analyst_output: {
              core_problem: row.extracted_problem || 'Pain point identified in submission',
              buying_intent: (row.user_intent as any) || 'high',
              evidence_quote: row.evidence_quote || row.title,
            },
            strategist_output: {
              opportunity_score: row.opportunity_score ?? 75,
              brand_risk: 'low',
              verdict: (row.engagement_decision as any) || 'engage',
              reasoning: row.strategic_reasoning || 'Qualified by Strategist agent',
            },
            draft_content: row.proposed_draft || 'Draft generated by Relay persona',
            critic_output: {
              critic_passed: Boolean(row.critic_passed),
              violation_category: row.violation_category,
              critic_feedback: row.critic_feedback,
            },
            status: row.status,
            iteration_count: row.draft_iteration || 1,
            created_at: row.discovered_at || new Date().toISOString(),
          }));
          setOpportunities(mapped);
        }
      }

      // Also sync community feed
      const feedRes = await fetch(`${API_BASE}/api/feed?limit=25`);
      if (feedRes.ok) {
        const feedData = await feedRes.json();
        if (feedData.items && feedData.items.length > 0) {
          const mappedFeed: IngestedPost[] = feedData.items.map((item: any) => ({
            thread_id: item.thread_id,
            subreddit: item.subreddit,
            title: item.title,
            author: item.author,
            timestamp: item.discovered_at ? new Date(item.discovered_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : 'Recent',
            status: item.status,
            score: item.opportunity_score,
          }));
          setLivePosts(mappedFeed);
        }
      }
    } catch (err) {
      console.log('Backend API unreachable, using local reactive state.');
    } finally {
      setIsRefreshing(false);
    }
  };

  useEffect(() => {
    fetchReviewQueue();
  }, []);

  // Handle Marketer Action (Approve / Edit / Reject)
  const handleActionComplete = async (
    threadId: string,
    action: 'approved' | 'edited' | 'rejected',
    text?: string,
    rejectionReason?: string
  ) => {
    try {
      await fetch(`${API_BASE}/api/review/${threadId}/submit`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action,
          edited_text: text || (rejectionReason ? `Reason: ${rejectionReason}` : undefined),
        }),
      });
    } catch (err) {
      console.log('Resumed via local reactive state.');
    }

    if (action === 'approved' || action === 'edited') {
      setApprovedCount((prev) => prev + 1);
    }

    // Update live posts stream status
    setLivePosts((prev) =>
      prev.map((p) =>
        p.thread_id === threadId
          ? { ...p, status: action === 'rejected' ? 'DISCARDED' : 'APPROVED' }
          : p
      )
    );
  };

  // Handle Quick Simulation Injection
  const handleSimulateIngest = async (title: string, body: string, subreddit: string) => {
    try {
      const res = await fetch(`${API_BASE}/api/ingest/simulate`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ title, body, subreddit }),
      });

      if (res.ok) {
        const data = await res.json();
        const opp = data.opportunity;
        if (opp) {
          const newPost: IngestedPost = {
            thread_id: opp.thread_id,
            subreddit: opp.subreddit,
            title: opp.title,
            author: opp.author,
            timestamp: 'Just now',
            status: opp.status,
            score: opp.opportunity_score,
          };
          setLivePosts((prev) => [newPost, ...prev]);

          if (opp.status === 'AWAITING_APPROVAL') {
            const mappedOpp: Opportunity = {
              id: opp.thread_id,
              thread_data: {
                thread_id: opp.thread_id,
                subreddit: opp.subreddit,
                title: opp.title,
                body: opp.body,
                author: opp.author,
                permalink: opp.permalink,
                created_utc: opp.created_utc,
              },
              analyst_output: {
                core_problem: opp.extracted_problem,
                buying_intent: opp.user_intent || 'high',
                evidence_quote: opp.evidence_quote || opp.title,
              },
              strategist_output: {
                opportunity_score: opp.opportunity_score,
                brand_risk: 'low',
                verdict: opp.engagement_decision || 'engage',
                reasoning: opp.strategic_reasoning,
              },
              draft_content: opp.proposed_draft,
              critic_output: {
                critic_passed: Boolean(opp.critic_passed),
                violation_category: opp.violation_category,
                critic_feedback: opp.critic_feedback,
              },
              status: opp.status,
              iteration_count: opp.draft_iteration || 1,
              created_at: opp.discovered_at || new Date().toISOString(),
            };
            setOpportunities((prev) => [mappedOpp, ...prev]);
          }
        }
      }
    } catch (err) {
      // Fallback local injection
      const mockId = `t3_local_${Math.random().toString(36).slice(2, 8)}`;
      const isSpam = title.toLowerCase().includes('seo') || title.toLowerCase().includes('discount');
      const score = isSpam ? 18 : 86;
      const status = isSpam ? 'DISCARDED' : 'AWAITING_APPROVAL';

      const mockPost: IngestedPost = {
        thread_id: mockId,
        subreddit,
        title,
        author: 'community_dev',
        timestamp: 'Just now',
        status,
        score,
      };
      setLivePosts((prev) => [mockPost, ...prev]);

      if (status === 'AWAITING_APPROVAL') {
        const newOpp: Opportunity = {
          id: mockId,
          thread_data: {
            thread_id: mockId,
            subreddit,
            title,
            body,
            author: 'community_dev',
            permalink: `https://reddit.com/${subreddit}`,
            created_utc: Date.now() / 1000,
          },
          analyst_output: {
            core_problem: 'Workflow friction identified in simulated post.',
            buying_intent: 'high',
            evidence_quote: title,
          },
          strategist_output: {
            opportunity_score: score,
            brand_risk: 'low',
            verdict: 'engage',
            reasoning: 'Strong tactical fit with problem-first engagement criteria.',
          },
          draft_content: 'The core bottleneck here is audio timestamp boundary detection rather than simple silence thresholding. Using token-level alignment prevents cuts from clipping words in half.',
          critic_output: {
            critic_passed: true,
            violation_category: null,
            critic_feedback: 'Passed zero-plug and compliance guardrails.',
          },
          status: 'AWAITING_APPROVAL',
          iteration_count: 1,
          created_at: new Date().toISOString(),
        };
        setOpportunities((prev) => [newOpp, ...prev]);
      }
    }
  };

  const pendingOpportunities = opportunities.filter((o) => o.status === 'AWAITING_APPROVAL');

  return (
    <div className="min-h-screen bg-dark-950 flex flex-col font-sans">
      <Navbar pendingCount={pendingOpportunities.length} approvedCount={approvedCount} />

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 flex-1 w-full">
        {/* Desk Header Info */}
        <div className="flex flex-wrap items-center justify-between gap-4 mb-8">
          <div>
            <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-white flex items-center gap-3">
              Marketer Review Desk
              <span className="text-xs font-semibold px-2.5 py-1 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                HITL Required
              </span>
            </h1>
            <p className="text-sm text-slate-400 mt-1">
              Pausing automatically at LangGraph <code className="text-indigo-300 font-mono text-xs">interrupt()</code> nodes. Review and authorize drafted replies before publication.
            </p>
          </div>

          <button
            type="button"
            onClick={fetchReviewQueue}
            disabled={isRefreshing}
            className="inline-flex items-center gap-2 px-3.5 py-2 rounded-lg bg-dark-850 hover:bg-dark-800 border border-slate-700 text-slate-300 text-xs font-medium transition-colors"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${isRefreshing ? 'animate-spin' : ''}`} />
            Refresh Queue
          </button>
        </div>

        {/* 2-Column Grid: Review Queue & Live Community Stream */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          {/* Main Triage Feed (8 cols) */}
          <div className="lg:col-span-8 space-y-6">
            <div className="flex items-center justify-between pb-3 border-b border-slate-800">
              <h2 className="text-base font-bold text-white uppercase tracking-wider flex items-center gap-2">
                <ShieldCheck className="w-4 h-4 text-indigo-400" />
                Opportunities Awaiting Human Authorization ({pendingOpportunities.length})
              </h2>
            </div>

            {pendingOpportunities.length === 0 ? (
              <div className="bg-dark-900/40 border border-slate-800/80 rounded-2xl p-12 text-center">
                <div className="w-12 h-12 rounded-full bg-emerald-500/10 text-emerald-400 flex items-center justify-center mx-auto mb-3 border border-emerald-500/20">
                  <CheckCircle2 className="w-6 h-6" />
                </div>
                <h3 className="text-base font-semibold text-white mb-1">Queue Clear</h3>
                <p className="text-xs text-slate-400 max-w-sm mx-auto">
                  All identified opportunities have been triaged. The background daemon is actively monitoring subreddits.
                </p>
              </div>
            ) : (
              pendingOpportunities.map((opp) => (
                <OpportunityCard
                  key={opp.id}
                  opportunity={opp}
                  onActionComplete={handleActionComplete}
                />
              ))
            )}
          </div>

          {/* Live Ingestion Feed Sidebar (4 cols) */}
          <div className="lg:col-span-4 sticky top-24">
            <LiveStreamFeed
              posts={livePosts}
              onSimulateIngest={handleSimulateIngest}
            />
          </div>
        </div>
      </main>
    </div>
  );
}
