'use client';

import React, { useState, useEffect } from 'react';
import { Navbar } from '../../components/Navbar';
import { OpportunityCard } from '../../components/OpportunityCard';
import { LiveStreamFeed } from '../../components/LiveStreamFeed';
import { Opportunity, IngestedPost } from '../../types';
import { INITIAL_OPPORTUNITIES, INITIAL_LIVE_POSTS } from '../../lib/mock-data';
import { getFeed, getReviewQueue, ingestCustom, submitReview } from '../../lib/api';
import { DashboardMetric } from '../../components/DashboardMetric';
import { AnimatePresence, motion, useReducedMotion } from 'motion/react';
import { Activity, CheckCircle2, Clock3, RadioTower, RefreshCw, ShieldCheck } from 'lucide-react';

export default function MarketerReviewDesk() {
  const [opportunities, setOpportunities] = useState<Opportunity[]>(INITIAL_OPPORTUNITIES);
  const [livePosts, setLivePosts] = useState<IngestedPost[]>(INITIAL_LIVE_POSTS);
  const [approvedCount, setApprovedCount] = useState(1);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const reduceMotion = useReducedMotion();

  // Fetch pending review queue from backend
  const fetchReviewQueue = async () => {
    try {
      setIsRefreshing(true);
      {
        const data = await getReviewQueue();
        const list = data.queue || data.opportunities;
        if (list && list.length > 0) {
          const mapped: Opportunity[] = list.map((row: any) => {
            let parsedEvidence = [row.evidence_quote || row.title];
            try {
              if (row.evidence) {
                parsedEvidence = typeof row.evidence === 'string' ? JSON.parse(row.evidence) : row.evidence;
              }
            } catch (e) {
              parsedEvidence = [row.evidence_quote || row.title];
            }

            let parsedBrands: string[] = [];
            try {
              if (row.mentioned_brands) {
                parsedBrands = typeof row.mentioned_brands === 'string' ? JSON.parse(row.mentioned_brands) : row.mentioned_brands;
              }
            } catch (e) {}

            return {
              id: row.thread_id,
              thread_data: {
                thread_id: row.thread_id,
                community_id: row.community_id || row.subreddit,
                subreddit: row.subreddit,
                title: row.title,
                body: row.body || '',
                author: row.author,
                permalink: row.permalink,
                created_utc: row.created_utc || Date.now() / 1000,
              },
              analyst_output: {
                core_problem: row.extracted_problem || 'Pain point identified in submission',
                pain_point: row.pain_point || 'Friction with manual workflows',
                user_goal: row.user_goal || 'Find reliable alternatives',
                community_context: row.community_context || '',
                buying_intent: (row.user_intent as any) || 'high',
                sentiment: row.sentiment || 'neutral',
                brand_mentioned: Boolean(row.brand_mentioned),
                competitor_mentioned: Boolean(row.competitor_mentioned),
                mentioned_brands: parsedBrands,
                evidence_quote: row.evidence_quote || row.title,
                evidence: parsedEvidence,
                analyst_confidence: row.analyst_confidence ?? 0.88,
              },
              strategist_output: {
                opportunity_score: row.opportunity_score ?? 75,
                relevance_score: row.relevance_score ?? 90,
                intent_strength_score: row.intent_strength_score ?? 85,
                community_fit_score: row.community_fit_score ?? 80,
                credibility_score: row.credibility_score ?? 85,
                engagement_risk_score: row.engagement_risk_score ?? 20,
                strategist_confidence: row.strategist_confidence ?? 0.88,
                brand_risk: 'low',
                verdict: (row.engagement_decision as any) || 'engage',
                reasoning: row.strategic_reasoning || 'Qualified by Strategist agent',
              },
              draft_content: row.proposed_draft || 'Draft generated by Relay persona',
              critic_output: {
                critic_passed: Boolean(row.critic_passed),
                violation_category: row.violation_category,
                critic_feedback: row.critic_feedback,
              },
              status: row.status,
              sensitive_topic: Boolean(row.sensitive_topic),
              sensitive_topic_reason: row.sensitive_topic_reason,
              iteration_count: row.draft_iteration || 1,
              created_at: row.discovered_at || new Date().toISOString(),
            };
          });
          setOpportunities(mapped);
        }
      }

      // Also sync community feed
      {
        const feedData = await getFeed();
        if (feedData.items && feedData.items.length > 0) {
          const mappedFeed: IngestedPost[] = feedData.items.map((item: any) => ({
            thread_id: item.thread_id,
            subreddit: item.subreddit,
            title: item.title,
            author: item.author,
            timestamp: item.discovered_at ? new Date(item.discovered_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : 'Recent',
            status: item.status,
            score: item.opportunity_score,
          }));
          setLivePosts(mappedFeed);
        }
      }
    } catch (err) {
      console.log('Backend API unreachable, using local reactive state.');
    } finally {
      setIsRefreshing(false);
    }
  };

  useEffect(() => {
    fetchReviewQueue();
  }, []);

  // Handle Marketer Action (Approve / Edit / Reject)
  const handleActionComplete = async (
    threadId: string,
    action: 'approved' | 'edited' | 'rejected',
    text?: string,
    rejectionReason?: any
  ) => {
    try {
      await submitReview(threadId, action, text, rejectionReason);
    } catch (err) {
      console.log('Resumed via local reactive state.');
    }

    if (action === 'approved' || action === 'edited') {
      setApprovedCount((prev) => prev + 1);
    }

    // Update live posts stream status
    setLivePosts((prev) =>
      prev.map((p) =>
        p.thread_id === threadId
          ? { ...p, status: action === 'rejected' ? 'DISCARDED' : 'APPROVED' }
          : p
      )
    );
  };

  // Handle Quick Simulation Injection
  const handleSimulateIngest = async (title: string, body: string, subreddit: string) => {
    try {
      {
        const data = await ingestCustom(title, body, subreddit);
        const opp = data.opportunity;
        if (opp) {
          const newPost: IngestedPost = {
            thread_id: opp.thread_id,
            subreddit: opp.subreddit,
            title: opp.title,
            author: opp.author,
            timestamp: 'Just now',
            status: opp.status,
            score: opp.opportunity_score,
          };
          setLivePosts((prev) => [newPost, ...prev]);

          if (opp.status === 'AWAITING_APPROVAL') {
            const mappedOpp: Opportunity = {
              id: opp.thread_id,
              thread_data: {
                thread_id: opp.thread_id,
                subreddit: opp.subreddit,
                title: opp.title,
                body: opp.body,
                author: opp.author,
                permalink: opp.permalink,
                created_utc: opp.created_utc,
              },
              analyst_output: {
                core_problem: opp.extracted_problem,
                buying_intent: opp.user_intent || 'high',
                evidence_quote: opp.evidence_quote || opp.title,
              },
              strategist_output: {
                opportunity_score: opp.opportunity_score,
                brand_risk: 'low',
                verdict: opp.engagement_decision || 'engage',
                reasoning: opp.strategic_reasoning,
              },
              draft_content: opp.proposed_draft,
              critic_output: {
                critic_passed: Boolean(opp.critic_passed),
                violation_category: opp.violation_category,
                critic_feedback: opp.critic_feedback,
              },
              status: opp.status,
              iteration_count: opp.draft_iteration || 1,
              created_at: opp.discovered_at || new Date().toISOString(),
            };
            setOpportunities((prev) => [mappedOpp, ...prev]);
          }
        }
      }
    } catch (err) {
      // Fallback local injection
      const mockId = `t3_local_${Math.random().toString(36).slice(2, 8)}`;
      const isSpam = title.toLowerCase().includes('seo') || title.toLowerCase().includes('discount');
      const score = isSpam ? 18 : 86;
      const status = isSpam ? 'DISCARDED' : 'AWAITING_APPROVAL';

      const mockPost: IngestedPost = {
        thread_id: mockId,
        subreddit,
        title,
        author: 'community_dev',
        timestamp: 'Just now',
        status,
        score,
      };
      setLivePosts((prev) => [mockPost, ...prev]);

      if (status === 'AWAITING_APPROVAL') {
        const newOpp: Opportunity = {
          id: mockId,
          thread_data: {
            thread_id: mockId,
            subreddit,
            title,
            body,
            author: 'community_dev',
            permalink: `https://reddit.com/${subreddit}`,
            created_utc: Date.now() / 1000,
          },
          analyst_output: {
            core_problem: 'Workflow friction identified in simulated post.',
            buying_intent: 'high',
            evidence_quote: title,
          },
          strategist_output: {
            opportunity_score: score,
            brand_risk: 'low',
            verdict: 'engage',
            reasoning: 'Strong tactical fit with problem-first engagement criteria.',
          },
          draft_content: 'The core bottleneck here is audio timestamp boundary detection rather than simple silence thresholding. Using token-level alignment prevents cuts from clipping words in half.',
          critic_output: {
            critic_passed: true,
            violation_category: null,
            critic_feedback: 'Passed zero-plug and compliance guardrails.',
          },
          status: 'AWAITING_APPROVAL',
          iteration_count: 1,
          created_at: new Date().toISOString(),
        };
        setOpportunities((prev) => [newOpp, ...prev]);
      }
    }
  };

  const pendingOpportunities = opportunities.filter((o) => o.status === 'AWAITING_APPROVAL');

  return (
    <div className="command-center min-h-screen flex flex-col font-sans">
      <Navbar pendingCount={pendingOpportunities.length} approvedCount={approvedCount} />

      <main className="max-w-[1480px] mx-auto px-4 sm:px-6 lg:px-8 py-8 lg:py-10 flex-1 w-full relative z-10">
        {/* Desk Header Info */}
        <motion.div initial={reduceMotion ? false : { opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="flex flex-wrap items-end justify-between gap-5 mb-8">
          <div>
            <p className="dash-eyebrow"><RadioTower className="h-3.5 w-3.5" aria-hidden="true" />Live operations</p>
            <h1 className="text-3xl sm:text-5xl font-bold tracking-[-0.045em] text-white">Signal review center</h1>
            <p className="text-sm text-slate-400 mt-3 max-w-2xl leading-6">Inspect evidence, validate agent reasoning, and authorize every response before it reaches a community.</p>
          </div>

          <button
            type="button"
            onClick={fetchReviewQueue}
            disabled={isRefreshing}
            className="dash-refresh"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${isRefreshing ? 'animate-spin' : ''}`} />
            Refresh Queue
          </button>
        </motion.div>

        <motion.section aria-label="System overview" className="dash-metrics" initial={reduceMotion ? false : { opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .08 }}>
          <DashboardMetric icon={Clock3} label="Awaiting review" value={pendingOpportunities.length} detail="Human decision required" tone="amber" />
          <DashboardMetric icon={Activity} label="Signals screened" value={livePosts.length} detail="Current feed window" tone="cyan" />
          <DashboardMetric icon={CheckCircle2} label="Authorized" value={approvedCount} detail="Approved this session" tone="green" />
          <DashboardMetric icon={ShieldCheck} label="Autoposted" value="0" detail="Safety gate enforced" tone="violet" />
        </motion.section>

        {/* 2-Column Grid: Review Queue & Live Community Stream */}
        <div className="grid grid-cols-1 xl:grid-cols-12 gap-6 items-start">
          {/* Main Triage Feed (8 cols) */}
          <section className="xl:col-span-8 space-y-5" aria-labelledby="queue-heading">
            <div className="flex items-center justify-between pb-3 border-b border-slate-800">
              <h2 id="queue-heading" className="text-sm font-bold text-white uppercase tracking-[.12em] flex items-center gap-2">
                <ShieldCheck className="w-4 h-4 text-indigo-400" />
                Opportunities Awaiting Human Authorization ({pendingOpportunities.length})
              </h2>
            </div>

            {pendingOpportunities.length === 0 ? (
              <div className="bg-dark-900/40 border border-slate-800/80 rounded-2xl p-12 text-center">
                <div className="w-12 h-12 rounded-full bg-emerald-500/10 text-emerald-400 flex items-center justify-center mx-auto mb-3 border border-emerald-500/20">
                  <CheckCircle2 className="w-6 h-6" />
                </div>
                <h3 className="text-base font-semibold text-white mb-1">Queue Clear</h3>
                <p className="text-xs text-slate-400 max-w-sm mx-auto">
                  All identified opportunities have been triaged. The background daemon is actively monitoring subreddits.
                </p>
              </div>
            ) : (
              <AnimatePresence initial={false}>{pendingOpportunities.map((opp, index) => <motion.div key={opp.id} initial={reduceMotion ? false : { opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, scale: .98 }} transition={{ delay: reduceMotion ? 0 : index * .05 }}><OpportunityCard opportunity={opp} onActionComplete={handleActionComplete} /></motion.div>)}</AnimatePresence>
            )}
          </section>

          {/* Live Ingestion Feed Sidebar (4 cols) */}
          <aside className="xl:col-span-4 xl:sticky xl:top-24">
            <LiveStreamFeed
              posts={livePosts}
              onSimulateIngest={handleSimulateIngest}
            />
          </aside>
        </div>
      </main>
    </div>
  );
}
